ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER airline IDENTIFIED BY strongpassword;

GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO airline;

ALTER USER airline DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;